# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tFfTQiE8FXzyBtVV4PJ0ueRb4Emm6xj3wJeiiKDPOls2uvEe2/KEhLAvemrWGZ65zEZeHlduFsW2oXz6JEYBiM4rfJg9r3POUfWK4mHaPSyKo8g1wmwfR7oFHo64nlQvT0FMzE/TzmK9KjRZAXkND9t0o6E/fsHYjrXvntuPL1cQDhHA1dK9ni+5ILgCGaPzkbPkvAxwFWVs0cfv8aZmTcEw1BerenkvrPGlLBHKRuhtOhsfa/bwuBKpckglPnhnKOSEMdjv3c/CmEHMbAAo1YzSgThXfJ9o0U7zGQC27O0a2ZlvM3BqbXUvOSkMTNPj46mpjIgMzo2IAoeaMZPuQYauAqfZanL8x2jtr27CywdMsOjYBL+L8n4TOoEDRd0kVWR5aK5Y4+Qu/3fmzEmbw64atpzUHi3Cn/Wx8i96GloGu16uepV6xqfkeNwyw7YwGHgfZcPfisfxMoS6my6PxKjqfQoCsStrtztf820Zgnr2HwGNmZGdZtfhs0mCDeTyyc0I6HX6OzCvOZk5AOW9Pe8oIDhkKE5na/CnbssRnHz5xZmDjz2NQkhGSqEs5Rth7EsSRHWhDvhBWPaYyI9AR6nI8uPL7MTGOIMIBMP6j2LsPE2uNEfAxBP6nxIGKpdmAozW0TLTxa6d7vuB9Si7NP7QADjVl7kc3hE0u96s7Dg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
